FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json .
COPY . .
RUN npm run build


FROM node:20-alpine
RUN apk --no-cache add curl
WORKDIR /app

COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json .

EXPOSE 5173
ENV NODE_ENV=development
CMD ["npm", "run", "dev", "--", "--host"]

