# Use an official OpenJDK runtime as a parent image
FROM openjdk:21-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Gradle wrapper and build files
COPY gradlew* gradle/ ./

# Copy the rest of the project files
COPY . .

# Give execution permissions to the Gradle wrapper
RUN chmod +x gradlew

# Build the application
RUN ./gradlew build -x test

# Expose the port the app runs on
EXPOSE 8080

# Define the command to run the app
CMD ["./gradlew", "bootRun"]
