version: '3.9'

services:
  go-server:
    build:
      context: ./chat-api
      dockerfile: Dockerfile.dev
    container_name: go-server
    ports:
      - "9009:9009"

  svelte-client:
    build:
      context: ./client/
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
    ports:
      - "3000:5173"

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local-redis:redis
    ports:
      - "8081:8081"
    depends_on:
      - redis

