version: '3.9'

services:
  go-server:
    build:
      context: ./chat-api
      dockerfile: Dockerfile.dev
    container_name: go-server
    ports:
      - "9009:9009"

  svelte-client:
    build:
      context: ./client/
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
    ports:
      - "3000:5173"

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local-redis:redis
    ports:
      - "8081:8081"
    depends_on:
      - redis

  postgres:
    image: "postgres:15-alpine"
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: chattydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  java-db:
    build:
      context: ./chatty-db
      dockerfile: Dockerfile.dev
    container_name: java-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chattydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgrespassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres

volumes:
  postgres_data:
